[gappdash]
# mode sets whether to list applications in a grid or list.
mode = "grid" # or "list"
# daemonize, if true, will ensure that the GApplication stays in the background
# if the window is closed the first time. This reduces startup time
# significantly after the first time.
daemonize = true
# index-age determines the maximum age for indexing application files. Once the
# index expires, spawning the window will still use the old index until the
# background task can finish renewing the index.
index-age = "15m"
# fuzzy, if true, will search for applications using fuzzy searching instead of
# regular substring searching.
fuzzy = true
# case-sensitive, if true, will treat upper-case letters the same as lower-case
# letters. This is only useful if fuzzy is false.
case-sensitive = false
# icon-size determines the size of each icon to appear in the grid/list.
icon-size = 52

[gappdash.grid]
max-children-per-line = 6
min-children-per-line = 6

[layer-shell]
# enable, if false, will make the gappdash window a regular window instead of an
# overlay. The regular window will have a titlebar.
enable = true
# layer can be "overlay", "top", "bottom", or "background".
layer = "overlay"
# anchors contains a list of edges to which the window will stick onto. Listing
# all 4 means in the middle (or fullscreen).
anchors = [ "top", "bottom", "left", "right" ]
# margins contains the margins for all 4 edges.
margins = { top = 0, bottom = 0, left = 0, right = 0 }

[window]
# width sets the width of the window, or 0 for fullscreen.
width  = 1000
# height sets the height of the window, or 0 for fullscreen.
height = 700
